name: Publish to PyPI via Trusted Publisher

on:
  push:
    tags:
      - "*"  

jobs:

  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Check version
        run: |
          TAG_NAME=$(echo ${{ github.ref_name }})
          PYVERSION_FILE="pygrt/_version.py"
          PYTHON_VERSION=$(grep -oP '__version__ = "\K[0-9]+\.[0-9]+\.[0-9]+' ${PYVERSION_FILE})
          CVERSION_FILE="pygrt/C_extension/version"
          C_VERSION=$(cat $CVERSION_FILE)

          if [ "$PYTHON_VERSION" != "${TAG_NAME:1}" ]; then
          echo "Version mismatch between tag and ${PYVERSION_FILE}"
          exit 1
          fi

          if [ "$C_VERSION" != "${PYTHON_VERSION%.*}" ]; then
          echo "Version mismatch between tag and ${CVERSION_FILE}"
          exit 1
          fi


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build

      - name: Build the package
        run: |
          python setup.py sdist # 暂不加bdist_wheel，先使用源码编译，后续会改进 

      - name: Pypi Publish
        uses: pypa/gh-action-pypi-publish@release/v1